import { fetchGoogleSheetsData } from "./index";
import { config } from "./config";
import { IOutputFormat } from "./IOutputFormat";
import * as fs from "fs";

describe("tests for fetchGoogleSheetsData()", () => {
  it("fetches data for multiple sheets and multiple sub sheets", async () => {
    const { file1, file2 } = config.demoFiles;
    const files = [file1, file2];
    const outputFormats: IOutputFormat[] = [
      "JSON_RAW",
      "JSON_COLUMNS",
      "JSON_ROWS",
    ];
    const result = await fetchGoogleSheetsData(files, outputFormats);

    expect(result).toEqual(expectedData);
  });
});

const expectedData = {
  "19VnV0Hu0IcwkIqUJndKeUNSSne2OvpLKSSccDiHPmw4": {
    "0": {
      JSON_RAW: {
        version: "0.6",
        reqId: "0",
        status: "ok",
        sig: "1627032852",
        table: {
          cols: [
            { id: "A", label: "", type: "string" },
            { id: "B", label: "", type: "string" },
            { id: "C", label: "", type: "string" },
            { id: "D", label: "", type: "string" },
            { id: "E", label: "", type: "string" },
            { id: "F", label: "", type: "string" },
            { id: "G", label: "", type: "string" },
            { id: "H", label: "", type: "string" },
            { id: "I", label: "", type: "string" },
            { id: "J", label: "", type: "string" },
            { id: "K", label: "", type: "string" },
            { id: "L", label: "", type: "string" },
            { id: "M", label: "", type: "string" },
            { id: "N", label: "", type: "string" },
            { id: "O", label: "", type: "string" },
            { id: "P", label: "", type: "string" },
            { id: "Q", label: "", type: "string" },
            { id: "R", label: "", type: "string" },
            { id: "S", label: "", type: "string" },
            { id: "T", label: "", type: "string" },
            { id: "U", label: "", type: "string" },
            { id: "V", label: "", type: "string" },
            { id: "W", label: "", type: "string" },
            { id: "X", label: "", type: "string" },
            { id: "Y", label: "", type: "string" },
            { id: "Z", label: "", type: "string" },
          ],
          rows: [
            {
              c: [
                { v: "monday" },
                { v: "tuesday" },
                { v: "wednesday" },
                { v: "thursday" },
                { v: "friday" },
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                { v: null },
              ],
            },
            {
              c: [
                { v: "taskA" },
                { v: "taskB" },
                { v: "taskC" },
                { v: "taskA" },
                { v: "taskB" },
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                { v: null },
              ],
            },
            {
              c: [
                { v: "taskB" },
                null,
                null,
                { v: "taskC" },
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                { v: null },
              ],
            },
            {
              c: [
                { v: "taskC" },
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                { v: null },
              ],
            },
          ],
          parsedNumHeaders: 0,
        },
      },
      JSON_COLUMNS: {
        A: {
          id: "A",
          label: "",
          type: "string",
          rows: { "0": "monday", "1": "taskA", "2": "taskB", "3": "taskC" },
        },
        B: {
          id: "B",
          label: "",
          type: "string",
          rows: { "0": "tuesday", "1": "taskB" },
        },
        C: {
          id: "C",
          label: "",
          type: "string",
          rows: { "0": "wednesday", "1": "taskC" },
        },
        D: {
          id: "D",
          label: "",
          type: "string",
          rows: { "0": "thursday", "1": "taskA", "2": "taskC" },
        },
        E: {
          id: "E",
          label: "",
          type: "string",
          rows: { "0": "friday", "1": "taskB" },
        },
        F: { id: "F", label: "", type: "string", rows: {} },
        G: { id: "G", label: "", type: "string", rows: {} },
        H: { id: "H", label: "", type: "string", rows: {} },
        I: { id: "I", label: "", type: "string", rows: {} },
        J: { id: "J", label: "", type: "string", rows: {} },
        K: { id: "K", label: "", type: "string", rows: {} },
        L: { id: "L", label: "", type: "string", rows: {} },
        M: { id: "M", label: "", type: "string", rows: {} },
        N: { id: "N", label: "", type: "string", rows: {} },
        O: { id: "O", label: "", type: "string", rows: {} },
        P: { id: "P", label: "", type: "string", rows: {} },
        Q: { id: "Q", label: "", type: "string", rows: {} },
        R: { id: "R", label: "", type: "string", rows: {} },
        S: { id: "S", label: "", type: "string", rows: {} },
        T: { id: "T", label: "", type: "string", rows: {} },
        U: { id: "U", label: "", type: "string", rows: {} },
        V: { id: "V", label: "", type: "string", rows: {} },
        W: { id: "W", label: "", type: "string", rows: {} },
        X: { id: "X", label: "", type: "string", rows: {} },
        Y: { id: "Y", label: "", type: "string", rows: {} },
        Z: {
          id: "Z",
          label: "",
          type: "string",
          rows: { "0": null, "1": null, "2": null, "3": null },
        },
      },
      JSON_ROWS: {
        "0": {
          id: 0,
          columns: {
            A: { id: "A", label: "", type: "string", data: "monday" },
            B: {
              id: "B",
              label: "",
              type: "string",
              data: "tuesday",
            },
            C: {
              id: "C",
              label: "",
              type: "string",
              data: "wednesday",
            },
            D: {
              id: "D",
              label: "",
              type: "string",
              data: "thursday",
            },
            E: { id: "E", label: "", type: "string", data: "friday" },
            F: { id: "F", label: "", type: "string" },
            G: { id: "G", label: "", type: "string" },
            H: { id: "H", label: "", type: "string" },
            I: { id: "I", label: "", type: "string" },
            J: { id: "J", label: "", type: "string" },
            K: { id: "K", label: "", type: "string" },
            L: { id: "L", label: "", type: "string" },
            M: { id: "M", label: "", type: "string" },
            N: { id: "N", label: "", type: "string" },
            O: { id: "O", label: "", type: "string" },
            P: { id: "P", label: "", type: "string" },
            Q: { id: "Q", label: "", type: "string" },
            R: { id: "R", label: "", type: "string" },
            S: { id: "S", label: "", type: "string" },
            T: { id: "T", label: "", type: "string" },
            U: { id: "U", label: "", type: "string" },
            V: { id: "V", label: "", type: "string" },
            W: { id: "W", label: "", type: "string" },
            X: { id: "X", label: "", type: "string" },
            Y: { id: "Y", label: "", type: "string" },
            Z: { id: "Z", label: "", type: "string", data: null },
          },
        },
        "1": {
          id: 1,
          columns: {
            A: { id: "A", label: "", type: "string", data: "taskA" },
            B: { id: "B", label: "", type: "string", data: "taskB" },
            C: { id: "C", label: "", type: "string", data: "taskC" },
            D: { id: "D", label: "", type: "string", data: "taskA" },
            E: { id: "E", label: "", type: "string", data: "taskB" },
            F: { id: "F", label: "", type: "string" },
            G: { id: "G", label: "", type: "string" },
            H: { id: "H", label: "", type: "string" },
            I: { id: "I", label: "", type: "string" },
            J: { id: "J", label: "", type: "string" },
            K: { id: "K", label: "", type: "string" },
            L: { id: "L", label: "", type: "string" },
            M: { id: "M", label: "", type: "string" },
            N: { id: "N", label: "", type: "string" },
            O: { id: "O", label: "", type: "string" },
            P: { id: "P", label: "", type: "string" },
            Q: { id: "Q", label: "", type: "string" },
            R: { id: "R", label: "", type: "string" },
            S: { id: "S", label: "", type: "string" },
            T: { id: "T", label: "", type: "string" },
            U: { id: "U", label: "", type: "string" },
            V: { id: "V", label: "", type: "string" },
            W: { id: "W", label: "", type: "string" },
            X: { id: "X", label: "", type: "string" },
            Y: { id: "Y", label: "", type: "string" },
            Z: { id: "Z", label: "", type: "string", data: null },
          },
        },
        "2": {
          id: 2,
          columns: {
            A: { id: "A", label: "", type: "string", data: "taskB" },
            B: { id: "B", label: "", type: "string" },
            C: { id: "C", label: "", type: "string" },
            D: { id: "D", label: "", type: "string", data: "taskC" },
            E: { id: "E", label: "", type: "string" },
            F: { id: "F", label: "", type: "string" },
            G: { id: "G", label: "", type: "string" },
            H: { id: "H", label: "", type: "string" },
            I: { id: "I", label: "", type: "string" },
            J: { id: "J", label: "", type: "string" },
            K: { id: "K", label: "", type: "string" },
            L: { id: "L", label: "", type: "string" },
            M: { id: "M", label: "", type: "string" },
            N: { id: "N", label: "", type: "string" },
            O: { id: "O", label: "", type: "string" },
            P: { id: "P", label: "", type: "string" },
            Q: { id: "Q", label: "", type: "string" },
            R: { id: "R", label: "", type: "string" },
            S: { id: "S", label: "", type: "string" },
            T: { id: "T", label: "", type: "string" },
            U: { id: "U", label: "", type: "string" },
            V: { id: "V", label: "", type: "string" },
            W: { id: "W", label: "", type: "string" },
            X: { id: "X", label: "", type: "string" },
            Y: { id: "Y", label: "", type: "string" },
            Z: { id: "Z", label: "", type: "string", data: null },
          },
        },
        "3": {
          id: 3,
          columns: {
            A: { id: "A", label: "", type: "string", data: "taskC" },
            B: { id: "B", label: "", type: "string" },
            C: { id: "C", label: "", type: "string" },
            D: { id: "D", label: "", type: "string" },
            E: { id: "E", label: "", type: "string" },
            F: { id: "F", label: "", type: "string" },
            G: { id: "G", label: "", type: "string" },
            H: { id: "H", label: "", type: "string" },
            I: { id: "I", label: "", type: "string" },
            J: { id: "J", label: "", type: "string" },
            K: { id: "K", label: "", type: "string" },
            L: { id: "L", label: "", type: "string" },
            M: { id: "M", label: "", type: "string" },
            N: { id: "N", label: "", type: "string" },
            O: { id: "O", label: "", type: "string" },
            P: { id: "P", label: "", type: "string" },
            Q: { id: "Q", label: "", type: "string" },
            R: { id: "R", label: "", type: "string" },
            S: { id: "S", label: "", type: "string" },
            T: { id: "T", label: "", type: "string" },
            U: { id: "U", label: "", type: "string" },
            V: { id: "V", label: "", type: "string" },
            W: { id: "W", label: "", type: "string" },
            X: { id: "X", label: "", type: "string" },
            Y: { id: "Y", label: "", type: "string" },
            Z: { id: "Z", label: "", type: "string", data: null },
          },
        },
      },
    },
    "1086688112": {
      JSON_RAW: {
        version: "0.6",
        reqId: "0",
        status: "ok",
        sig: "776943751",
        table: {
          cols: [
            { id: "A", label: "", type: "string" },
            { id: "B", label: "", type: "string" },
          ],
          rows: [
            { c: [null, { v: "some lost cell 1" }] },
            { c: [null, { v: "some lost cell 2" }] },
          ],
          parsedNumHeaders: 0,
        },
      },
      JSON_COLUMNS: {
        A: { id: "A", label: "", type: "string", rows: {} },
        B: {
          id: "B",
          label: "",
          type: "string",
          rows: { "0": "some lost cell 1", "1": "some lost cell 2" },
        },
      },
      JSON_ROWS: {
        "0": {
          id: 0,
          columns: {
            A: { id: "A", label: "", type: "string" },
            B: {
              id: "B",
              label: "",
              type: "string",
              data: "some lost cell 1",
            },
          },
        },
        "1": {
          id: 1,
          columns: {
            A: { id: "A", label: "", type: "string" },
            B: {
              id: "B",
              label: "",
              type: "string",
              data: "some lost cell 2",
            },
          },
        },
      },
    },
    "2100601117": {
      JSON_RAW: {
        version: "0.6",
        reqId: "0",
        status: "ok",
        sig: "128801331",
        table: {
          cols: [{ id: "A", label: "", type: "string" }],
          rows: [{ c: [{ v: "Hello World" }] }],
          parsedNumHeaders: 0,
        },
      },
      JSON_COLUMNS: {
        A: {
          id: "A",
          label: "",
          type: "string",
          rows: { "0": "Hello World" },
        },
      },
      JSON_ROWS: {
        "0": {
          id: 0,
          columns: {
            A: {
              id: "A",
              label: "",
              type: "string",
              data: "Hello World",
            },
          },
        },
      },
    },
  },
  "197U_3ZQaL7jN0sPZvKPhQRN-1tKfwr_VXL09b8W5zpI": {
    "0": {
      JSON_RAW: {
        version: "0.6",
        reqId: "0",
        status: "ok",
        sig: "1674099795",
        table: {
          cols: [{ id: "A", label: "", type: "string" }],
          rows: [
            { c: [{ v: "Shopping List" }] },
            { c: [{ v: "apples" }] },
            { c: [{ v: "bananas" }] },
            { c: [{ v: "oranges" }] },
            { c: [{ v: "walnuts" }] },
          ],
          parsedNumHeaders: 0,
        },
      },
      JSON_COLUMNS: {
        A: {
          id: "A",
          label: "",
          type: "string",
          rows: {
            "0": "Shopping List",
            "1": "apples",
            "2": "bananas",
            "3": "oranges",
            "4": "walnuts",
          },
        },
      },
      JSON_ROWS: {
        "0": {
          id: 0,
          columns: {
            A: {
              id: "A",
              label: "",
              type: "string",
              data: "Shopping List",
            },
          },
        },
        "1": {
          id: 1,
          columns: {
            A: { id: "A", label: "", type: "string", data: "apples" },
          },
        },
        "2": {
          id: 2,
          columns: {
            A: { id: "A", label: "", type: "string", data: "bananas" },
          },
        },
        "3": {
          id: 3,
          columns: {
            A: { id: "A", label: "", type: "string", data: "oranges" },
          },
        },
        "4": {
          id: 4,
          columns: {
            A: { id: "A", label: "", type: "string", data: "walnuts" },
          },
        },
      },
    },
    "201058147": {
      JSON_RAW: {
        version: "0.6",
        reqId: "0",
        status: "ok",
        sig: "286462470",
        table: {
          cols: [{ id: "A", label: "", type: "string" }],
          rows: [
            { c: [{ v: "open tasks" }] },
            { c: [{ v: "do laundry" }] },
            { c: [{ v: "grocery shopping" }] },
          ],
          parsedNumHeaders: 0,
        },
      },
      JSON_COLUMNS: {
        A: {
          id: "A",
          label: "",
          type: "string",
          rows: {
            "0": "open tasks",
            "1": "do laundry",
            "2": "grocery shopping",
          },
        },
      },
      JSON_ROWS: {
        "0": {
          id: 0,
          columns: {
            A: {
              id: "A",
              label: "",
              type: "string",
              data: "open tasks",
            },
          },
        },
        "1": {
          id: 1,
          columns: {
            A: {
              id: "A",
              label: "",
              type: "string",
              data: "do laundry",
            },
          },
        },
        "2": {
          id: 2,
          columns: {
            A: {
              id: "A",
              label: "",
              type: "string",
              data: "grocery shopping",
            },
          },
        },
      },
    },
  },
};
